export const QUERY_KEYS = {
  TENANTS: "tenants",
  TENANT_DETAILS: "tenant_details",
  USERS: "users",
  AUTH_PROFILE: "auth-profile",
  SUBSCRIPTION_PLANS: "subscription-plans",
  SETTINGS: "settings",
  ACADEMIC_YEARS: "academic-years",
  ACADEMIC_CLASSES: "academic-classes",
  STUDENTS: "students",
  STUDENT_DETAILS: "student-details",
  STUDENT_HISTORY: "student-history",
  ACADEMIC_SUBJECTS: "academic-subjects",
  TIMETABLE_CONFIGURATIONS: "timetable-configurations",
  TIMETABLE_CONFIGURATION_DAYS: "timetable-configuration-days",
  TIMETABLE_CONFIGURATION_PERIODS: "timetable-configuration-periods",
  TIMETABLES: "timetables",
} as const;
